### ISSUE TITLE
No option to edit post on mobile

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1397] opened 2021-10-13 18:46 UTC
**Describe the bug**
I cannot edit a post on mobile

**To Reproduce**
Tap the 3 dots on a post

**Expected behavior**
There should be an edit entry and edit functionality

**Screenshots**
![Screen Shot 2021-10-13 at 1 32 18 PM](https://user-images.githubusercontent.com/15471332/137194572-633c5593-3a43-4eb1-a42c-54c14ee871ba.png)

**Platform**
Chrome, MetaMask

**Comment by SeverS** [comment] 2021-10-14 05:49
duplicate of https://github.com/AKASHAorg/akasha-world-framework/issues/1382

**Closed as completed** 2021-10-20 21:26 UTC
Labels: bug, duplicate
