### ISSUE TITLE
The graph on the stats UI has a overlapping issues when using the Metamask app browser.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1340] opened 2021-09-29 20:48 UTC
**Describe the bug**
Upon navigating on the stats UI while using the Metamask app browser, the graph is exceeding its placeholder and the graph's legends are overlapping on each other.

**To Reproduce**
1. Download the Metamask application from Google Play.
2. Open the Metamask browser.
3. Visit the webpage https://ethereum-world.netlify.app/moderation-app/history.
4. Tap the "Stats" button.
5. Scroll down until the graph displays.
6. Observe the graph.

**Expected behavior**
The graph should not be exceeded its placeholder and the graph legends should be displayed properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/79607355/135345736-a8ec16fc-cc26-44e7-818e-66a20c41d79c.png)

**Smartphone (please complete the following information):**
HTC U12+ | 8
iPad 9.7 (5th Gen) | 13.6
-MetaMask Browser | Version v3.3.0 (777)

**Additional context**
Unable to verify on other devices due to limited resources.

**Wallet Used:**
MetaMask Web App

(NJPDR)

cc:@ggolcher

**Comment by kenshyx** [comment] 2021-09-30 10:31
duplicate of https://github.com/AKASHAorg/akasha-world-framework/issues/1330

**Closed as completed** 2021-09-30 10:32 UTC
Labels: bug, duplicate
