### ISSUE TITLE
[Desktop] The moderator's name is cut off when hovering the cursor to the profile icon of the moderator account on the Moderation History Page.

### ISSUE THREAD

**Issue by EPforAkasha** [AKASHAorg/akasha-world-framework#1430] opened 2021-10-16 06:04 UTC
**Describe the bug**
When hovering the cursor on the profile icon of the moderator accounts, the names of the moderators appears to be cut off.

**To Reproduce**
1. Navigate to the Moderation History Page.
2. Hover the mouse cursor to any of the listed profile icons of the moderators.
3. Check the name displayed.

**Expected behavior**
The full names of the moderators should be displayed when hovering the cursor to the profile icon of the moderator account on the Moderation History Page.

**Screenshots**
![cut off name_issue_sc](https://user-images.githubusercontent.com/79607355/137575611-14ce4010-9563-4e38-bb29-bba47501d894.jpg)

**Desktop:**
- Desktop | Windows 10 Pro
-- Chrome Version 94.0.4606.71
-- Firefox Version 93.0
- Apple iMac (21.5 Inch 2017) | macOS Big Sur Version 11.5.2
-- Safari Version 14.1.2
-- Chrome Version 93.0.4577.63 (Official Build) (x86_64)

EP (MMB)

cc:@ggolcher

**Comment by ghost** [comment] 2021-10-18 05:44
duplicate of #1426

**Closed as completed by ghost** 2021-10-18 05:44 UTC
Labels: duplicate
